# fly.toml app configuration file generated for omaaraguirre-portfolio on 2023-08-07T18:49:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "omaaraguirre-portfolio"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
