name: Deploy Workflows
on:
  push:
    branches: [main]

jobs:
  mocha-deploy:
    name: Deploy to Mocha
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: ./app/dist/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

  railway-deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install packages
        run: npm install --frozen-lockfile
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy to Railway
        run: railway up --service=omaaraguirre
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
